# Docker Compose pour tester localement avant le déploiement sur Render
version: "3.8"

services:
  # Base de données PostgreSQL
  postgres:
    image: postgres:16-alpine
    container_name: altn72-db-local
    environment:
      POSTGRES_DB: projet_java
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: apppass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U appuser -d projet_java"]
      interval: 10s
      timeout: 5s
      retries: 3

  # Application Spring Boot
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: altn72-app-local
    environment:
      SPRING_PROFILES_ACTIVE: prod
      DATABASE_URL: jdbc:postgresql://postgres:5432/projet_java?user=appuser&password=apppass
      JAVA_OPTS: -Xmx512m -Xms256m
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local
