databases:
  - name: altn72-projet-java-db
    databaseName: altn72_projet_java
    user: altn72_user
    plan: free
    region: frankfurt

services:
  - type: web
    name: altn72-projet-java-app
    runtime: docker
    region: frankfurt
    plan: free
    branch: main
    healthCheckPath: /actuator/health
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: altn72-projet-java-db
          property: connectionString
      - key: PORT
        value: 8080
      - key: DDL_AUTO
        value: update
      - key: SHOW_SQL
        value: false
      - key: JAVA_OPTS
        value: "-Xmx512m -Xms256m"
      - key: SPRING_PROFILES_ACTIVE
        value: prod
