services:
  # Base de données PostgreSQL
  - type: pserv
    name: projet-postgres
    env: docker
    plan: free
    region: frankfurt
    ipAllowList: []

  # Application Web Spring Boot
  - type: web
    name: projet-java-app
    env: docker
    region: frankfurt
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: projet-postgres
          property: connectionString
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: projet-postgres
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: projet-postgres
          property: password
      - key: SPRING_JPA_HIBERNATE_DDL_AUTO
        value: update
      - key: SPRING_JPA_DATABASE_PLATFORM
        value: org.hibernate.dialect.PostgreSQLDialect
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: PORT
        value: 8080
    healthCheckPath: /actuator/health

